export const BOOK_LIST_REQUEST= 'BOOK_LIST_REQUEST';

export const BOOK_LIST_SUCCESS= 'BOOK_LIST_SUCCESS'

export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';



export const BOOK_ADD_REQUEST= 'BOOK_ADD_REQUEST'

export const BOOK_ADD_SUCCESS= 'BOOK_ADD_SUCESS'

export const BOOK_ADD_FAIL= 'BOOK_ADD_FAIL'



export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST'

export const BOOK_UPDATE_SUCCESS= 'BOOK_UPDATE_SUCESS'

export const BOOK_UPDATE_FAIL= 'BOOK_UPDATE_FAIL'


export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST'

export const BOOK_DELETE_SUCCESS= 'BOOK_DELETE_SUCESS'

export const BOOK_DELETE_FAIL= 'BOOK_DELETE_FAIL'